#!/bin/bash

################################################################################
# DNS Monitoring - Universal Deployment Script
# Deploy to anywhere: Unraid, VPS, Cloud, Home Server, etc.
# Usage: ./deploy.sh
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✅${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

log_error() {
    echo -e "${RED}❌${NC} $1"
}

# Check prerequisites
check_requirements() {
    log_info "Checking requirements..."

    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi

    log_success "Docker and Docker Compose found"
}

# Get deployment configuration from user
get_deployment_config() {
    echo ""
    log_info "=========================================="
    log_info "DNS Monitoring - Deployment Configuration"
    log_info "=========================================="
    echo ""

    # Get deployment type
    echo "What is your deployment target?"
    echo "  1) IP address (e.g., 192.168.1.100)"
    echo "  2) Domain name (e.g., example.com)"
    echo "  3) Domain with custom port (e.g., example.com:3000)"
    read -p "Choose [1-3]: " DEPLOY_TYPE

    case $DEPLOY_TYPE in
        1)
            read -p "Enter IP address: " DEPLOY_HOST
            DEPLOY_DOMAIN="http://${DEPLOY_HOST}"
            API_URL="http://${DEPLOY_HOST}/api"
            USE_SSL=false
            ;;
        2)
            read -p "Enter domain name: " DEPLOY_HOST
            read -p "Use HTTPS/SSL? (y/n) [default: n]: " USE_SSL_INPUT
            if [[ "$USE_SSL_INPUT" == "y" || "$USE_SSL_INPUT" == "Y" ]]; then
                DEPLOY_DOMAIN="https://${DEPLOY_HOST}"
                API_URL="https://${DEPLOY_HOST}/api"
                USE_SSL=true
            else
                DEPLOY_DOMAIN="http://${DEPLOY_HOST}"
                API_URL="http://${DEPLOY_HOST}/api"
                USE_SSL=false
            fi
            ;;
        3)
            read -p "Enter domain with port (e.g., example.com:3000): " DEPLOY_HOST
            read -p "Use HTTPS/SSL? (y/n) [default: n]: " USE_SSL_INPUT
            if [[ "$USE_SSL_INPUT" == "y" || "$USE_SSL_INPUT" == "Y" ]]; then
                DEPLOY_DOMAIN="https://${DEPLOY_HOST}"
                API_URL="https://${DEPLOY_HOST}/api"
                USE_SSL=true
            else
                DEPLOY_DOMAIN="http://${DEPLOY_HOST}"
                API_URL="http://${DEPLOY_HOST}/api"
                USE_SSL=false
            fi
            ;;
        *)
            log_error "Invalid choice. Exiting."
            exit 1
            ;;
    esac

    echo ""
    log_info "Optional: Configure additional settings"

    read -p "Container prefix [default: dns-monitoring]: " CONTAINER_PREFIX
    CONTAINER_PREFIX=${CONTAINER_PREFIX:-dns-monitoring}

    read -p "External port [default: 80]: " EXTERNAL_PORT
    EXTERNAL_PORT=${EXTERNAL_PORT:-80}

    read -p "Timezone [default: Asia/Singapore]: " TIMEZONE
    TIMEZONE=${TIMEZONE:-Asia/Singapore}

    read -p "Default DNS Server [default: 1.1.1.1]: " DEFAULT_DNS_SERVER
    DEFAULT_DNS_SERVER=${DEFAULT_DNS_SERVER:-1.1.1.1}

    read -p "Data retention days [default: 30]: " RETENTION_DAYS
    RETENTION_DAYS=${RETENTION_DAYS:-30}

    echo ""
    log_info "Configuration Summary:"
    echo "  Deployment Domain: $DEPLOY_DOMAIN"
    echo "  API URL: $API_URL"
    echo "  Container Prefix: $CONTAINER_PREFIX"
    echo "  External Port: $EXTERNAL_PORT"
    echo "  Timezone: $TIMEZONE"
    echo "  Default DNS Server: $DEFAULT_DNS_SERVER"
    echo "  Data Retention: ${RETENTION_DAYS}d"
    echo "  SSL/HTTPS: $USE_SSL"
    echo ""

    read -p "Proceed with deployment? (y/n): " CONFIRM
    if [[ ! "$CONFIRM" == "y" && ! "$CONFIRM" == "Y" ]]; then
        log_info "Deployment cancelled."
        exit 0
    fi
}

# Create environment file
create_env_file() {
    log_info "Creating environment configuration file..."

    cat > .env.prod << EOF
# DNS Monitoring Production Environment
# Auto-generated by deploy.sh

# Node.js & Server
NODE_ENV=production
PORT=3000

# Frontend Configuration
VITE_API_URL=${API_URL}

# Backend Configuration
CORS_ORIGIN=${DEPLOY_DOMAIN}
DEFAULT_DNS_SERVER=${DEFAULT_DNS_SERVER}
QUERY_TIMEOUT_MS=5000
LOG_LEVEL=info
QUERY_RETENTION_DAYS=${RETENTION_DAYS}

# System Configuration
TZ=${TIMEZONE}

# Docker Compose Variables
CONTAINER_PREFIX=${CONTAINER_PREFIX}
EXTERNAL_PORT=${EXTERNAL_PORT}

# Deployment Info
DEPLOYED_AT=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
DEPLOYED_TO=${DEPLOY_DOMAIN}
EOF

    log_success "Environment file created: .env.prod"
}

# Create backup of existing data (if any)
backup_existing_data() {
    if [ -d "dns-data" ]; then
        log_warning "Existing data volume found"
        read -p "Backup before deploying? (y/n) [default: y]: " BACKUP_CONFIRM
        BACKUP_CONFIRM=${BACKUP_CONFIRM:-y}

        if [[ "$BACKUP_CONFIRM" == "y" || "$BACKUP_CONFIRM" == "Y" ]]; then
            BACKUP_DIR="backups/backup-$(date +%Y%m%d-%H%M%S)"
            mkdir -p "$BACKUP_DIR"
            cp -r dns-data/* "$BACKUP_DIR/" 2>/dev/null || true
            log_success "Backup created: $BACKUP_DIR"
        fi
    fi
}

# Pull latest image
pull_latest_image() {
    log_info "Pulling latest image from GHCR..."

    if docker pull ghcr.io/freemen810/dns-monitoring:latest; then
        log_success "Image pulled successfully"
    else
        log_error "Failed to pull image"
        log_info "Make sure you have internet connection and GHCR access"
        exit 1
    fi
}

# Deploy using docker-compose
deploy_container() {
    log_info "Starting deployment..."

    # Stop existing containers if any
    if docker-compose -f docker-compose.prod.yml ps 2>/dev/null | grep -q dns-monitoring; then
        log_warning "Stopping existing containers..."
        docker-compose -f docker-compose.prod.yml down || true
    fi

    # Deploy with env file
    if docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d; then
        log_success "Containers deployed successfully"
    else
        log_error "Failed to deploy containers"
        exit 1
    fi
}

# Wait for services to be healthy
wait_for_health() {
    log_info "Waiting for services to become healthy..."

    local max_attempts=30
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        if docker-compose -f docker-compose.prod.yml exec -T backend curl -s http://localhost:3000/api/health > /dev/null 2>&1; then
            log_success "Backend is healthy"
            return 0
        fi

        echo -n "."
        sleep 2
        attempt=$((attempt + 1))
    done

    log_warning "Services did not report healthy after ${max_attempts} attempts"
    log_info "This may be normal for slow systems. Check with: docker-compose logs"
}

# Display deployment info
show_deployment_info() {
    echo ""
    log_success "=========================================="
    log_success "Deployment Complete!"
    log_success "=========================================="
    echo ""
    echo "📍 Access your application at:"
    echo "   ${GREEN}${DEPLOY_DOMAIN}${NC}"
    echo ""
    echo "📡 API is available at:"
    echo "   ${GREEN}${API_URL}${NC}"
    echo ""
    echo "🔧 Useful commands:"
    echo "   View logs:        docker-compose -f docker-compose.prod.yml logs -f"
    echo "   Stop:             docker-compose -f docker-compose.prod.yml down"
    echo "   Restart:          docker-compose -f docker-compose.prod.yml restart"
    echo "   Health check:     curl ${DEPLOY_DOMAIN}/api/health"
    echo ""
    echo "💾 Data location:"
    echo "   Database volume:  dns-data/"
    echo "   Backups:          backups/"
    echo ""
    echo "📝 Configuration:"
    echo "   Environment:      .env.prod"
    echo "   Docker Compose:   docker-compose.prod.yml"
    echo "   Nginx config:     nginx.conf"
    echo ""

    if [ "$USE_SSL" = true ]; then
        echo "${YELLOW}⚠️  SSL/HTTPS Detected${NC}"
        echo "   Ensure your SSL certificates are in: ./ssl/"
        echo "   Files needed:"
        echo "     - ./ssl/cert.pem (SSL certificate)"
        echo "     - ./ssl/key.pem  (SSL private key)"
        echo ""
        echo "   Get free SSL with Let's Encrypt:"
        echo "   ${BLUE}certbot certonly --standalone -d ${DEPLOY_HOST}${NC}"
        echo ""
    fi

    echo "🆘 Need help? Check the logs:"
    echo "   ${BLUE}docker-compose -f docker-compose.prod.yml logs${NC}"
    echo ""
}

# Main execution
main() {
    clear
    echo ""
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║  DNS Monitoring - Universal Deployment Script         ║"
    echo "║  Deploy anywhere: Unraid, VPS, Cloud, Home Server     ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""

    check_requirements
    get_deployment_config
    create_env_file
    backup_existing_data
    pull_latest_image
    deploy_container
    wait_for_health
    show_deployment_info
}

# Run main function
main
